<a href="https://colab.research.google.com/github/NaDaGyeong/ml-for-AI/blob/main/9_22_w4_teamwork_%EB%82%98%EB%8B%A4%EA%B2%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd /content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02/

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02

In [3]:
import pandas as pd
df = pd.read_csv('data/earthquakes.csv')

In [4]:
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...

# Task1

## Try loc and iloc function to select 3:10 items for mag, magType, and type variables

In [8]:
df.loc[3:10, ['mag', 'magType','type']]

     mag magType        type
3   0.44      ml  earthquake
4   2.16      md  earthquake
5   2.61      md  earthquake
6   1.70      ml  earthquake
7   1.13      md  earthquake
8   0.92      md  earthquake
9   4.70      mb  earthquake
10  0.50      ml  earthquake

In [23]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [11]:
df.iloc[3:10, [8,9,21]]

    mag magType        type
3  0.44      ml  earthquake
4  2.16      md  earthquake
5  2.61      md  earthquake
6  1.70      ml  earthquake
7  1.13      md  earthquake
8  0.92      md  earthquake
9  4.70      mb  earthquake

# Try to find items of location Arizona

In [14]:
df.loc[(df.place.str.contains('Arizona'))]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
1062,NaN,NaN,60300227,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.1666,NaN,163.0,",uu60300227,",1.23,ml,...,",uu,",reviewed,1539133978610,"M 1.2 - 7km SSW of Colorado City, Arizona",0,earthquake,",geoserve,origin,phase-data,",-420.0,1539196068710,https://earthquake.usgs.gov/earthquakes/eventp...
3965,NaN,NaN,60298572,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.1577,NaN,211.0,",uu60298572,",0.94,md,...,",uu,",reviewed,1538383710020,"M 0.9 - 7km WSW of Colorado City, Arizona",0,earthquake,",geoserve,origin,phase-data,",-420.0,1538516934720,https://earthquake.usgs.gov/earthquakes/eventp...

# Try to find 10 largest iems of mag variable

In [20]:
df['mag'].sort_values(ascending=False)[:10]

5263    7.5
837     7.0
4363    6.7
118     6.7
799     6.5
816     6.2
838     6.1
5323    6.1
9211    6.0
862     6.0
Name: mag, dtype: float64

In [21]:
df.mag.sort_values(ascending=False)[:10]

5263    7.5
837     7.0
4363    6.7
118     6.7
799     6.5
816     6.2
838     6.1
5323    6.1
9211    6.0
862     6.0
Name: mag, dtype: float64

# Task2

## Try to delete alert variable

In [25]:
df.drop('alert', axis=1, inplace=True)

In [26]:
df

,cdi,code,detail,dmin,felt,gap,ids,mag,magType,mmi,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,NaN,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,NaN,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,NaN,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,NaN,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,NaN,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,NaN,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,NaN,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,NaN,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,NaN,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,NaN,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

## Try to pop mag and magType variables one at a time with name mag, and magType

In [44]:
mag = df.pop('mag')

In [45]:
magType=df.pop('magType')

## Concatenate mag and magType variables and define a new DataFrame using.concat function

In [54]:
new_df = pd.concat([mag, magType], axis=1) # axis=1 !!

In [55]:
new_df

       mag magType
0     1.35      ml
1     1.29      ml
2     3.42      ml
3     0.44      ml
4     2.16      md
...    ...     ...
9327  0.62      md
9328  1.00      ml
9329  2.40      md
9330  1.10      ml
9331  0.66      ml

[9332 rows x 2 columns]